# Generated by Django 5.0.3 on 2026-02-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_scheduledtransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtransfer',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='scheduledtransfer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='secret_seed',
            field=models.CharField(max_length=256),
        ),
    ]
